spring:
  application:
    name: selman01
  datasource:
    url: jdbc:mysql://localhost:3306/web_01
    username: root
    password: hSelMan%231?!
    driver-class-name: com.mysql.cj.jdbc


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true